name: Build and Package for MacOS

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install "pyobjc-framework-Quartz>=10.3.1,<10.4"
          pip install -r requirements.txt

      - name: Compile resources
        run: |
          source venv/bin/activate
          cd screenvivid
          python compile_resources.py

      - name: Build with PyInstaller
        run: |
          source venv/bin/activate
          cd packaging/macos
          pyinstaller --clean --noconfirm screenvivid.spec

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Create DMG
        run: |
          cd packaging/macos
          create-dmg \
            --volname "ScreenVivid" \
            --volicon "../../screenvivid/resources/icons/screenvivid.icns" \
            --window-pos 0 0 \
            --icon-size 100 \
            --icon "ScreenVivid.app" 175 120 \
            --hide-extension "ScreenVivid.app" \
            --app-drop-link 425 120 \
            "ScreenVivid-${{ github.ref_name }}.dmg" \
            "dist/ScreenVivid.app"

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: ScreenVivid-${{ github.ref_name }}.dmg
          path: ScreenVivid-${{ github.ref_name }}.dmg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ScreenVivid-${{ github.ref_name }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}